name: douradelivery_app
description: DouraDelivery App Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.6
  
  # HTTP Client
  dio: ^5.4.0
  
  # Storage
  shared_preferences: ^2.2.2
  
  # State Management
  provider: ^6.1.0
  
  # Maps
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  
  # WebSocket
  web_socket_channel: ^2.4.0
  
  # Notifications
  flutter_local_notifications: ^16.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

